services:
  nginx-file-server:
    image: nginx:alpine
    container_name: nginx-file-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/usr/share/nginx/html:ro
      - ./data/logs:/var/log/nginx
    ports:
      - "8080:80"
    restart: always

  fluentbit:
    image: fluent/fluent-bit:latest

    container_name: fluentbit
    volumes:
      - ./fluentbit-config:/fluent-bit/etc
      - ./data/logs:/var/log/nginx:ro
      - ./data/output:/fluent-bit/out
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    ports:
      - "2020:2020"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always

  ubuntu:
    image: ubuntu
    container_name: ubuntu
    command: "bash"