services:
  fluentbit:
    image: fluent/fluent-bit:latest
    # build: .
    container_name: fluentbit
    volumes:
      - ./fluentbit-config:/fluent-bit/etc
      - ./data/logs:/var/log/nginx:ro
      # Mount a local output directory into /fluent-bit/out
      - ./data/output:/fluent-bit/out
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    ports:
      - "2020:2020"
    restart: always
  nginx-file-server:
    image: nginx:alpine
    container_name: nginx-file-server
    volumes:
      # Mount custom nginx configuration
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

      # Serve local "html" folder at /usr/share/nginx/html in the container
      - ./data:/usr/share/nginx/html:ro

      # (Optional) Store logs on the host
      - ./data/logs:/var/log/nginx

    ports:
      - "8080:80"    # Access the file server at http://localhost:8080
    restart: always
